### ISSUE TITLE
Document how to populate database

### ISSUE THREAD

**Issue by patcon** [designcofounders/toronto-city-hall-api#1]
Not sure how the postgres db is being populated. Would generally be great to have some project spin-up instructions.

**Comment by patcon** [comment]
~~More generally, I have tons of experience working with open source projects and what's involved in opensource stewardship, and I've love to help you get these two repos to a point where any developer Alice or Bob could drop in and set this up and start messing with it~~

~~And yes, I know I know, "you feel it's not ready yet", right? That's honestly the gut feeling of every person with their first open/collaborative project, and all I can say is that you really need to suppress that feeling, because it's usually unhelpful :)~~

:heart:

EDIT: On second thought, let's leave the general FOSS convo for elsewhere, as I'm conflating issues :)

**Comment by dougestey** [comment]
I'll have these up tonight!

**Comment by patcon** [comment]
Yay!

**Comment by dougestey** [comment]
I've been doing some thinking about the best way to populate the database in a fresh environment. Sails doesn't really have a convention for this, and councillor data is not constant and therefore shouldn't be implemented as fixtures. 

The most seemingly relevant method, as mentioned by one of the Sails developers [here](http://stackoverflow.com/questions/24090135/loading-data-fixtures-the-first-time-a-sails-js-app-is-lifted), is to use Waterline syntax to inject it in the [bootstrap](https://github.com/designcofounders/toronto-city-hall-api/blob/master/config/bootstrap.js) phase. This really is a similar problem to the above, however, and would require writing/maintaining code for the 40+ councillors in Toronto city hall.

So I think I'm going to provide a Postgres DB in the repo to get people up and running. It's what seems to make the most sense.

**Comment by dougestey** [comment]
@patcon I updated the project setup readme. This will get you up and running with a properly structured DB, albeit empty.

**Comment by patcon** [comment]
thanks dude!

**Comment by dougestey** [comment]
Marking this as closed, as I think the method of obtaining data to insert into the db is a different/non-issue altogether.
