### ISSUE TITLE
Continuously updated motions (bills) data

### ISSUE THREAD

**Issue by jpmckinney** [designcofounders/toronto-city-hall-api#10]
The scraper for the API at https://scrapers.herokuapp.com/bills isn't being actively run (because it was an experiment, I didn't know anyone was using the data, and the scraper takes a lot longer to run than our representatives scrapers). I can have the scraper run daily, just let me know.

**Comment by dougestey** [comment]
@jpmckinney Our plan was to have this run as a job on the API staging instance - but if you're happy to take on that task with this one, we're happy to offload it to you.

**Comment by jpmckinney** [comment]
I've added a job to run daily.
